# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WinkEvents.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "com.test.package.WinkEvent" do
    optional :timestamp, :int64, 1
    optional :eye_color, :enum, 2, "com.test.package.EyeColor"
    optional :duration, :int32, 3
    optional :is_pretty, :bool, 4
    optional :impression, :string, 5
  end
  add_enum "com.test.package.EyeColor" do
    value :BROWN, 0
    value :BLUE, 1
    value :GREEN, 2
    value :GREY, 3
  end
end

module Com
  module Test
    module Package
      WinkEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("com.test.package.WinkEvent").msgclass
      EyeColor = Google::Protobuf::DescriptorPool.generated_pool.lookup("com.test.package.EyeColor").enummodule
    end
  end
end
